<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class DeleteModuleCommand extends Command
{
    //php artisan make:module-delete event-category
    // Are you sure you want to permanently delete the 'EventCategory' module?
    // php artisan make:module-delete event-category --force
    protected $signature = 'make:module-delete
                            {name : The module name}
                            {--force : Skip confirmation prompt}
                            {--rollback : Rollback this module migration before deleting}
                            {--refresh : Refresh the database after deleting}';

    protected $description = 'Delete a module and all files generated by make:module';

    public function handle(): int
    {
        $module = Str::studly($this->argument('name'));

        $table = Str::snake(Str::pluralStudly($module));
        $kebab = Str::kebab($module);
        $pluralFolder = Str::kebab(Str::plural($module));

        $modulePath = base_path("app/Modules/{$module}");
        $routePath = base_path("routes/back-office/{$kebab}.php");
        $viewsPath = resource_path("views/back-office/{$pluralFolder}");

        $migrationGlob = base_path(
            "database/migrations/*_create_{$table}_table.php"
        );

        $bindingsFile = app_path('Modules/bindings.php');

        $this->newLine();

        $this->info("🗑️ Module: {$module}");
        $this->line("   Table:  {$table}");
        $this->line("   Route:  {$routePath}");
        $this->line("   Views:  {$viewsPath}");

        $this->newLine();

        if (!$this->option('force')) {
            if (!$this->confirm(
                "Are you sure you want to permanently delete the '{$module}' module?"
            )) {
                $this->warn('Operation cancelled.');

                return self::SUCCESS;
            }
        }

        /*
        |--------------------------------------------------------------------------
        | 1. Rollback Module Migration
        |--------------------------------------------------------------------------
        */

        if ($this->option('rollback')) {
            $this->rollbackModuleMigration($module, $migrationGlob);
        }

        /*
        |--------------------------------------------------------------------------
        | 2. Delete Module Directory
        |--------------------------------------------------------------------------
        */

        if (File::exists($modulePath)) {
            File::deleteDirectory($modulePath);

            $this->info("✅ Module deleted: {$modulePath}");
        } else {
            $this->warn("⚠️ Module directory not found: {$modulePath}");
        }

        /*
        |--------------------------------------------------------------------------
        | 3. Delete Route
        |--------------------------------------------------------------------------
        */

        if (File::exists($routePath)) {
            File::delete($routePath);

            $this->info("✅ Route deleted: {$routePath}");
        } else {
            $this->warn("⚠️ Route file not found: {$routePath}");
        }

        /*
        |--------------------------------------------------------------------------
        | 4. Delete Blade Views
        |--------------------------------------------------------------------------
        */

        if (File::exists($viewsPath)) {
            File::deleteDirectory($viewsPath);

            $this->info("✅ Views deleted: {$viewsPath}");
        } else {
            $this->warn("⚠️ Views directory not found: {$viewsPath}");
        }

        /*
        |--------------------------------------------------------------------------
        | 5. Remove Repository Binding
        |--------------------------------------------------------------------------
        */

        $this->removeRepositoryBinding($module, $bindingsFile);

        /*
        |--------------------------------------------------------------------------
        | 6. Delete Migration File
        |--------------------------------------------------------------------------
        */

        $this->deleteMigration($migrationGlob, $module);

        /*
        |--------------------------------------------------------------------------
        | 7. Optional Database Refresh
        |--------------------------------------------------------------------------
        */

        if ($this->option('refresh')) {
            if (!$this->option('force')) {
                if (!$this->confirm(
                    'Do you want to refresh the entire database? This will rollback and re-run ALL migrations.',
                    false
                )) {
                    $this->newLine();
                    $this->info("🎯 Module '{$module}' deleted successfully.");

                    return self::SUCCESS;
                }
            }

            $this->newLine();
            $this->info('🔄 Refreshing database...');

            Artisan::call('migrate:refresh');

            $this->line(Artisan::output());
        }

        $this->newLine();

        $this->info("🎯 Module '{$module}' completely deleted.");

        return self::SUCCESS;
    }

    /*
    |--------------------------------------------------------------------------
    | Rollback Module Migration
    |--------------------------------------------------------------------------
    */

    protected function rollbackModuleMigration(
        string $module,
        string $migrationGlob
    ): void {
        $migrations = glob($migrationGlob);

        if (empty($migrations)) {
            $this->warn("⚠️ No migration found for {$module}.");

            return;
        }

        foreach ($migrations as $migration) {
            $relativePath = str_replace(
                base_path() . DIRECTORY_SEPARATOR,
                '',
                $migration
            );

            $this->info("🔄 Rolling back: {$relativePath}");

            Artisan::call('migrate:rollback', [
                '--path' => $relativePath,
            ]);

            $output = Artisan::output();

            if (trim($output)) {
                $this->line($output);
            }
        }
    }

    /*
    |--------------------------------------------------------------------------
    | Delete Migration
    |--------------------------------------------------------------------------
    */

    protected function deleteMigration(
        string $migrationGlob,
        string $module
    ): void {
        $migrations = glob($migrationGlob);

        if (empty($migrations)) {
            $this->warn("⚠️ No migration file found for {$module}.");

            return;
        }

        foreach ($migrations as $migration) {
            File::delete($migration);

            $this->info("✅ Migration deleted: {$migration}");
        }
    }

    /*
    |--------------------------------------------------------------------------
    | Remove Repository Binding
    |--------------------------------------------------------------------------
    */

    protected function removeRepositoryBinding(
        string $module,
        string $bindingsFile
    ): void {
        if (!File::exists($bindingsFile)) {
            return;
        }

        $bindings = require $bindingsFile;

        $contract = "App\\Modules\\{$module}\\Repositories\\Contracts\\{$module}Contract";

        if (!isset($bindings[$contract])) {
            $this->warn("⚠️ Binding not found for {$module}.");

            return;
        }

        unset($bindings[$contract]);

        $content = "<?php\n\nreturn [\n";

        foreach ($bindings as $key => $value) {
            $content .= "    \\{$key}::class => \\{$value}::class,\n";
        }

        $content .= "];\n";

        File::put($bindingsFile, $content);

        $this->info("✅ Repository binding removed: {$contract}");
    }
}
